### ISSUE TITLE
Cannot set collapse_every_n_layers via Python bindings

### ISSUE THREAD

**Issue by osma** [tomtung/parabel-rs#12]
Hi,

I'm trying to figure out how to use the AttentionXML-like hyperparameters mentioned in the top level README using the Python bindings. This would require setting the `collapse_every_n_layers` hyperparameter to 5.

It appears to me that this hyperparameter is not exposed to the Python bindings (nor to the C API). There is no field called `collapse_every_n_layers` (or anything similar) in the HyperParam object returned by `omikuji.Model.default_hyper_param()`. In fact, the only source files that mention this hyperparameter are `src/bin/omikuji.rs` and `src/model/train.rs` so it is only used within the Rust implementation, not in any of the bindings.

**Comment by tomtung** [comment]
Should be fixed in the newest release.

**Comment by osma** [comment]
Thanks, this was fast! It works very well now in version 0.2.0.
