### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by travisbrady** [tomtung/parabel-rs#2]
Thanks again for this library and craft-ml. I have a few questions about the file format.

1. Must labels be integers or can they just be strings?
2. Can feature indexes be arbitrary unique integers (using feature hashing for instance) or must they be sequential?
3. Have you compared craft-ml against parabel-rs? Do they behave similarly? Any recommendations for one over the other?

thanks

**Comment by tomtung** [comment]
My implementation craftml came close but didn't fully match the performance reported in the paper; even if it did, it would still be worse than parabel. So I'd recommend trying parabel first.

The current parabel implementation assumes labels to be integers, and assumes feature indices to be sequential.

Out of curiosity, what application are you planning to use it for?

**Comment by travisbrady** [comment]
Thanks, Tom.

I'm planning to use this for query autocompletion and perhaps similar query suggestion.
