### ISSUE TITLE
golang binding via c-api possible?

### ISSUE THREAD

**Issue by trpstra** [tomtung/parabel-rs#20]
Thanks a lot for this great lib, it's wonderful!

This is not an issue per se, more like a question. I would like to use omikuji in my application, which is currently written in golang. I think my options are to use the python api in a small dedicated prediction server, or to somehow create a golang binding myself. I am not very familiar with rust, do you think the current c-api can be used to generate the necessary stub C code for such a binding (with cgo)? If you happen to have some pointers or advice on how to do that, I would love to hear it.
(Maybe adding a REST server option to omikuji itself could be a fun project too, if I ever find some time to learn rust...)

Thanks again!

**Comment by tomtung** [comment]
I don't really have much experience with Go, but using the C binding should be feasible in theory. You can go to the `c-api` directory and run `cargo build --release`. After it has finished, you should find the C header file `c-api/target/include/omikuji.h`, archive libraries file `c-api/target/release/libomikuji.a` for static linking, and shared object file `c-api/target/release/libomikuji.so` for dynamic linking.

**Comment by osma** [comment]
Hi @onclue, you may want to look at [Annif](http://annif.org) - it's a tool for text classification/labeling/tagging with support for Omikuji as a backend (which works great btw!) and a REST API. If your app happens to need a service like this, it could bridge the gap between it and Omikuji.

**Comment by trpstra** [comment]
Thanks a lot @tomtung , I will give that a try!

Thanks for the hint, @osma . Annif looks interesting, but if it is also a python REST server around Omikuji I would prefer to try the direct integration option first.
