### ISSUE TITLE
Different models (and results) while training on the same data

### ISSUE THREAD

**Issue by rabitwhte** [tomtung/parabel-rs#28]
Hey @tomtung,

it's me again. I noticed that I get different results for the models that were trained on the same data, with the same hyper parameters. Is that possible? Is it because there is some randomness in label partitioning? Can I control that somehow (by specifying random state?)

Regards,
rabitwhte

**Comment by tomtung** [comment]
Hey sorry about the delay.

Yes this behavior is expected. To maximize parallelization, the code tries to distribute work dynamically to the available workers at runtime, and it's very hard to know in advance the exact order of all the "get random number" operations. So even for the same hyperparameters, the same work could be distributed to different workers, and as a result even fixing a random seed wouldn't resolve this uncertainty.

Closing for now, but feel free to reopen if you have other suggestions :)
