### ISSUE TITLE
Wheel for Python 3.9?

### ISSUE THREAD

**Issue by juhoinkinen** [tomtung/parabel-rs#30]
Hi and thanks for the great library! We are using Omikuji in one backend of [Annif](https://github.com/NatLibFi/Annif), and it is performing very well in the subject indexing task.

As the title says, we are wondering if it would be possible to have wheel for Python 3.9 (for Linux) in PyPI? It would simplify installation into Docker image. Now for installing Omikuji on Python 3.9 it seems it is necessary to have also cargo installed (at least).

**Comment by tomtung** [comment]
Yeah, unfortunately, the building pipeline is currently broken, probably caused by Azure silently updating some part of their building env :( I can try to look into this later and see if I can get it fixed.

**Comment by tomtung** [comment]
A new version has been published to PyPI with all the wheels. Please let me know if you encounter any issues.
