### ISSUE TITLE
thread 'main' panicked at 'Could not determine the UTC offset on this system

### ISSUE THREAD

**Issue by follperson** [tomtung/parabel-rs#37]
I've been running this on linux via AWS SageMaker for some experimentation with Twitter hashtags and I think the new releases changed something relating to the simple-logger update. I reverted back to 0.3.3 and everything works. 

I really appreciate this implementation tho! it is very quick and efficient for testing out some extreme classification pipelines, thanks for writing it up!

## Backtrace

thread 'main' panicked at 'Could not determine the UTC offset on this system. Possible causes are that the time crate does not implement "local_offset_at" on your system, or that you are running in a multi-threaded environment and the time crate is returning "None" from "local_offset_at" to avoid unsafe behaviour. See the time crate's documentation for more information. (https://time-rs.github.io/internal-api/time/index.html#feature-flags): IndeterminateOffset', /home/ec2-user/.cargo/registry/src/github.com-1ecc6299db9ec823/simple_logger-1.15.1/src/lib.rs:360:64
stack backtrace:
   0:     0x556ab1b7413d - std::backtrace_rs::backtrace::libunwind::trace::hf6a6dfd7da937cb0
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x556ab1b7413d - std::backtrace_rs::backtrace::trace_unsynchronized::hc596a19e4891f7f3
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x556ab1b7413d - std::sys_common::backtrace::_print_fmt::hb16700db31584325
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x556ab1b7413d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h231c4190cfa75162
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x556ab1b147cc - core::fmt::write::h2a1462b5f8eea807
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/fmt/mod.rs:1163:17
   5:     0x556ab1b72cb4 - std::io::Write::write_fmt::h71ddfebc68685972
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/io/mod.rs:1696:15
   6:     0x556ab1b73360 - std::sys_common::backtrace::_print::hcc197d4bebf2b369
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x556ab1b73360 - std::sys_common::backtrace::print::h335a66af06738c7c
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x556ab1b73360 - std::panicking::default_hook::{{closure}}::h6fac9ac9c8b79e52
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:210:50
   9:     0x556ab1b7278a - std::panicking::default_hook::h341c1030c6a1161b
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:227:9
  10:     0x556ab1b7278a - std::panicking::rust_panic_with_hook::h50680ff4b44510c6
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:624:17
  11:     0x556ab1b92608 - std::panicking::begin_panic_handler::{{closure}}::h9371c0fbb1e8465a
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:521:13
  12:     0x556ab1b92586 - std::sys_common::backtrace::__rust_end_short_backtrace::h9b3efa22a5768c0f
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:139:18
  13:     0x556ab1b92542 - rust_begin_unwind
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
  14:     0x556ab1a850e0 - core::panicking::panic_fmt::h23b9203e89cc61cf
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
  15:     0x556ab1a853c2 - core::result::unwrap_failed::h32ef6b3156e8fc57
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1616:5
  16:     0x556ab1b6ebdd - <simple_logger::SimpleLogger as log::Log>::log::h1c34c8b7ef19bacc
  17:     0x556ab1b230a2 - omikuji::data::DataSet::load_xc_repo_data_file::hb7a7cb9826b9150f
  18:     0x556ab1ac19ea - omikuji::train::h3d9bcb33a544581f
  19:     0x556ab1acda31 - omikuji::main::h382f86dabe280b2b
  20:     0x556ab1ab4c63 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9a5620b049f38e48
  21:     0x556ab1ad23f9 - main
  22:     0x7f6556dff585 - __libc_start_main
  23:     0x556ab1a902a5 - <unknown>
  24:                0x0 - <unknown>

### Notes

Seems like the same problem as noted here:
https://github.com/ravenclaw900/DietPi-Dashboard/issues/82

**Comment by tomtung** [comment]
Thanks for raising this issue! I'm currently on vacation and don't have access to my PC. In the meantime, can you help try out the fix from https://github.com/ravenclaw900/DietPi-Dashboard/commit/a3853c2697d5a0606499c41fc6cf456543e01a4e and see if that solves your issue? If that works, I'll push and release the same fix as soon as I get back.

**Comment by tomtung** [comment]
According to https://github.com/borntyping/rust-simple_logger/issues/52, the easiest thing to do is probably to upgrade `simple_logger` to the latest version. Will try that.
