### ISSUE TITLE
predict API

### ISSUE THREAD

**Issue by ljmartin** [tomtung/parabel-rs#4]
Hi, 
Thanks for parabel and making it available! I've had some promising results already. 

I'm using the python bindings and Im wondering about the API. Are there any kwargs I can use? For example, `model.predict(test_example)` returns the top ten ranked labels. Can I return all the rankings? Ive tried reading the source code but I just don't understand it sorry!

**Comment by tomtung** [comment]
You can look at the method signature:
https://github.com/tomtung/parabel-rs/blob/c367075a1defbbecc9b6e66a34720e89db920840/python/parabel/__init__.py#L48

You can use the `top_k` kwarg to control how many labels to return. Fewer labels might be returned if you use relatively small `beam_size`, or if you set small `max_leaf_size` during training. In these cases you can also try enlarging them.

**Comment by ljmartin** [comment]
Much appreciated
