### ISSUE TITLE
Wheel for Python 3.10

### ISSUE THREAD

**Issue by juhoinkinen** [tomtung/parabel-rs#43]
It would be nice to have a wheel for Python 3.10 in PyPI, especially now when Ubuntu 22.04 has been released with 3.10 as the default Python version. It would make installing Omikuji more straightforward (the version of cargo in apt repositories is too old for Omikuji, and I struggled some time [to install a new enough cargo version in Dockerfile](https://github.com/NatLibFi/Annif/issues/589#issuecomment-1109703384)).

**Comment by osma** [comment]
Any chance of including the Python 3.10 wheels in a release?

**Comment by tomtung** [comment]
> Any chance of including the Python 3.10 wheels in a release?

The 3.10 wheels were already uploaded for v0.5.0 I think?

**Comment by osma** [comment]
Ah, right, I didn't realize that this didn't require a new release. Thanks!
