### ISSUE TITLE
Installation problem and wheels for Python 3.11 and 3.12

### ISSUE THREAD

**Issue by juhoinkinen** [tomtung/parabel-rs#49]
Could wheels be provided for Python 3.11 and just-released 3.12 to ease installation?

Also, I was unable to install Omikuji on Python 3.11 at all, due to a regexp error by Milksnake, see https://github.com/NatLibFi/Annif/issues/703#issuecomment-1614513903.

It might be that there will not be a new Milksnake release including the fix for this; it has alredy been some time since the fix has been merged to master. So, a least-effort option on Omikuji side seems to be to install current Milksnake master. (I checked [this works](https://github.com/juhoinkinen/omikuji/commit/9f30e2ceefdad8d312e8d34357caf7ed81920ff4).)

Alternatively, some projects have [replaced Milksnake by Maturin](https://github.com/pyocd/cmsis-pack-manager/pull/195), which might be a more involved, but also a long-term solution.

BTW, you might want also to update the [classifiers for supported Python versions in `setup.py`](https://github.com/tomtung/omikuji/blob/master/setup.py#L51C5-L55C49) too.

**Comment by tomtung** [comment]
Yeah migrating from milksnake to maturin is probably the way to go. I'll try figure out how to do this, but I've been a bit busy lately, so if you manage to figure it out in the meantime, please don't hesitate to open a pull request.

**Comment by juhoinkinen** [comment]
Actually just a few days ago, Oct 12, [milksnake v0.1.6 was published on PyPI](https://pypi.org/project/milksnake/0.1.6/), which seems to include the required fix. The new version is used e.g. in https://github.com/getsentry/relay/pull/2599.

So for having support for Python 3.11 and 3.12 I think milksnake is still usable.

Anyway, I'll open a PR just for the 3.11 and 3.12 support. I could look at the maturin migration at later time, but I don't have any experience on Rust programs, so it might take some time.

**Comment by tomtung** [comment]
New wheels published with version 0.5.1.
