### ISSUE TITLE
Regarding code execution

### ISSUE THREAD

**Issue by purviprajapati196** [tomtung/parabel-rs#5]
Dear Sir/Madam,
We have tried to install parabel-rs package as per the instructions given in repository. But during build process it is unable to find some directory. we are using python3.6+.

Below screenshot for the error. 

![image](https://user-images.githubusercontent.com/38319034/62755424-9ab3a700-ba91-11e9-8050-c365b0dffe45.png)

**Comment by tomtung** [comment]
Can you paste the full error log as well as your environment info (OS, Python distribution, Cargo version, etc)?

**Comment by tomtung** [comment]
Feel free to re-open if this is not resolved.
