### ISSUE TITLE
regarding code

### ISSUE THREAD

**Issue by purviprajapati196** [tomtung/parabel-rs#9]
Dear Sir,

I have installed the cargo on ubuntu 18.04 and also run the training and testing on the Eurlex dataset and got the result in the form of a text file. So hereby attaching the screenshot of text file. 

But sir, I would like to generate results in form of p@1,p@3,p@5....
How could i get it? 
Kindly help me regarding this. I was stuck on this.
![r1 (1) (1)](https://user-images.githubusercontent.com/38319034/67923431-d3b47100-fbd3-11e9-9ae4-7b85051b4fdd.JPG)

**Comment by tomtung** [comment]
p@1, 2, & 5 are printed to the console. Your train & eval session should look like this: https://asciinema.org/a/QsY43zuNAAJl2EudZYnnqdMe0 Note that the precision numbers are printed to the last line.
